COMPANY_TYPES_FIELD = "companyTypes"
COLLECTOR_TYPES_FIELD = "collectorTypes"
WASTE_PROCESSOR_TYPES_FIELD = "wasteProcessorTypes"
WASTE_VEHICLE_TYPES_FIELD = "wasteVehiclesTypes"

TYPES_FIELDS = [
    COMPANY_TYPES_FIELD,
    COLLECTOR_TYPES_FIELD,
    WASTE_PROCESSOR_TYPES_FIELD,
    WASTE_VEHICLE_TYPES_FIELD,
]

ETABLISSEMENTS_CREATE_FIELDS = [
    "siret",
    "gerepId",
    COMPANY_TYPES_FIELD,
    COLLECTOR_TYPES_FIELD,
    WASTE_PROCESSOR_TYPES_FIELD,
    WASTE_VEHICLE_TYPES_FIELD,
    "givenName",
    "contactEmail",
    "contactPhone",
    "contact",
    "website",
]


ETABLISSEMENTS_UPDATE_FIELDS = [
    "siret",
    COMPANY_TYPES_FIELD,
    COLLECTOR_TYPES_FIELD,
    WASTE_PROCESSOR_TYPES_FIELD,
    WASTE_VEHICLE_TYPES_FIELD,
]

ROLES_FIELDS = [
    "siret",
    "email",
    "role",
]
USER_ROLES = ["MEMBER", "ADMIN", "DRIVER", "READER"]
COMPANY_TYPES = [
    "PRODUCER",
    "COLLECTOR",
    "WASTEPROCESSOR",
    "TRANSPORTER",
    "WASTE_VEHICLES",
    "WASTE_CENTER",
    "TRADER",
    "ECO_ORGANISME",
    "BROKER",
    "WORKER",
    "INTERMEDIARY",
    "DISPOSAL_FACILITY",
    "RECOVERY_FACILITY",
]
COLLECTOR_TYPES = [
    "NON_DANGEROUS_WASTES",
    "DANGEROUS_WASTES",
    "DEEE_WASTES",
    "OTHER_NON_DANGEROUS_WASTES",
    "OTHER_DANGEROUS_WASTES",
]
WASTE_PROCESSOR_TYPES = [
    "DANGEROUS_WASTES_INCINERATION",
    "NON_DANGEROUS_WASTES_INCINERATION",
    "CREMATION",
    "DANGEROUS_WASTES_STORAGE",
    "NON_DANGEROUS_WASTES_STORAGE",
    "INERT_WASTES_STORAGE",
    "OTHER_DANGEROUS_WASTES",
    "OTHER_NON_DANGEROUS_WASTES",
]
WASTE_VEHICLE_TYPES = ["BROYEUR", "DEMOLISSEUR"]
MIN_ETAB_ROW = 1
MAX_ETAB_CREATE_COL = 7
MAX_ETAB_UPDATE_COL = 5
MIN_ROLE_ROW = 1
MAX_ROLE_COL = 3
ERROR_STR = "💣 [red]Error[/red]"
VALID_STR = "[green]✔[/green]"
